resources:
  repositories:
    - repository: templates
      type: github
      endpoint: github
      name: ccdc-opensource/conan-azure-devops
      ref: refs/heads/development

extends:
  template: third-party-library-all-platforms-from-local-recipe.yml@templates
  parameters:
    package: ccdcsqlite3
    package_version: 3.45.1
    destination_repository: ccdc-3rdparty-conan
